import bcrypt from 'bcryptjs';
const data = {
  // users: [
  //   {
  //     name: 'John',
  //     email: 'admin@example.com',
  //     password: bcrypt.hashSync('123456'),
  //     isAdmin: true,
  //   },
  //   {
  //     name: 'Jane',
  //     email: 'user@example.com',
  //     password: bcrypt.hashSync('123456'),
  //     isAdmin: false,
  //   },
  // ],
  classes: [
    {
      id: 1,
      category: 'Kids',
      location: 'Ft. Laurderdale',
      name: 'ACTING FOR RUGRATS',
      slug: 'acting-for-rugrats',
      description:
        'This fast- paced, high energy class will introduce and explore the fundamental principles of Improvisation through simple short form games and exercises.  This class will help students strengthen their mental agility, creativity, ensemble work and patience in a fun and entertaining environment. If your child is interested in pursuing camera and film work in South Florida or beyond, this class is highly encouraged. ',
      age: '4-5-6-7-8',
      image: '/img/kids.jpg',
      teacher: 'Elena Maria Garcia',
      shedule: 'Saturday mornings 9:00 - 9:45 am',
      days: 'abr, abr7 ab 8, bar9,ar 10 abr 11',
      duration: '1 hr 30 min',
      price: 100,
      subtitle: 'Acting Classes for Kids & Adults that deliver results!',
      direccion: ['99 SW 14th Street', 'FL33315'],
      countInStock: 3,
    },
    {
      id: 2,
      category: 'Teens',
      location: 'Miami',
      name: 'ACTING / IMPROV FOR KIDS',
      slug: 'improv-for-kids',
      description:
        'This fast- paced, high energy class will introduce and explore the fundamental principles of Improvisation through simple short form games and exercises.  This class will help students strengthen their mental agility, creativity, ensemble work and patience in a fun and entertaining environment. If your child is interested in pursuing camera and film work in South Florida or beyond, this class is highly encouraged. ',
      age: '12-14-15',
      image: '/img/kids2.jpg',
      teacher: 'Elena Maria Garcia',
      shedule: 'Saturday mornings 9:00 - 9:45 am',
      days: '1/15, 1/22, 1/29, 2/5, 2/1, 2/19',
      duration: '6 weeks',
      price: 150,
      subtitle: 'Acting Classes for Kids & Adults that deliver results!',
      direccion: ['99 SW 14th Street', 33315],
      countInStock: 5,
    },
    {
      id: 3,
      category: 'Adult',
      location: 'Ft. Laurderdale',
      name: 'ACTING FOR RUGRATS',
      slug: 'acting-for-rugrats1',
      description:
        'This fast- paced, high energy class will introduce and explore the fundamental principles of Improvisation through simple short form games and exercises.  This class will help students strengthen their mental agility, creativity, ensemble work and patience in a fun and entertaining environment. If your child is interested in pursuing camera and film work in South Florida or beyond, this class is highly encouraged. ',
      age: '6-7-8-9',
      image: '/img/kids3.jpg',
      teacher: 'Elena Maria Garcia',
      shedule: 'Saturday mornings 9:00 - 9:45 am',
      days: '1/15, 1/22, 1/29, 2/5, 2/1, 2/19',
      duration: '6 weeks',
      price: 120,
      subtitle: 'Acting Classes for Kids & Adults that deliver results!',
      direccion: ['99 SW 14th Street', 33315],
      countInStock: 5,
    },
    {
      id: 4,
      category: 'Kids',
      location: 'Ft. Laurderdale',
      name: 'ACTING FOR RUGRATS',
      slug: 'acting-for-rugrats2',
      description:
        'This fast- paced, high energy class will introduce and explore the fundamental principles of Improvisation through simple short form games and exercises.  This class will help students strengthen their mental agility, creativity, ensemble work and patience in a fun and entertaining environment. If your child is interested in pursuing camera and film work in South Florida or beyond, this class is highly encouraged. ',
      age: '4-5-6-7',
      image: '/img/kids4.jpg',
      teacher: 'Elena Maria Garcia',
      shedule: 'Saturday mornings 9:00 - 9:45 am',
      days: '1/15, 1/22, 1/29, 2/5, 2/1, 2/19',
      duration: '6 weeks',
      price: 100,
      subtitle: 'Acting Classes for Kids & Adults that deliver results!',
      direccion: ['99 SW 14th Street', 33315],
      countInStock: 5,
    },
    {
      id: 5,
      category: 'Kids',
      location: 'Miami',
      name: 'ACTING FOR RUGRATS',
      slug: 'acting-for-rugrats3',
      description:
        'This fast- paced, high energy class will introduce and explore the fundamental principles of Improvisation through simple short form games and exercises.  This class will help students strengthen their mental agility, creativity, ensemble work and patience in a fun and entertaining environment. If your child is interested in pursuing camera and film work in South Florida or beyond, this class is highly encouraged. ',
      age: '4-5-6',
      image: '/img/kids5.jpg',
      teacher: 'Elena Maria Garcia',
      shedule: 'Saturday mornings 9:00 - 9:45 am',
      days: '1/15, 1/22, 1/29, 2/5, 2/1, 2/19',
      duration: '6 weeks',
      price: 120,
      subtitle: 'Acting Classes for Kids & Adults that deliver results!',
      direccion: ['99 SW 14th Street', 33315],
      countInStock: 5,
    },
    {
      id: 6,
      category: 'Kids',
      location: 'Ft. Laurderdale',
      name: 'ACTING FOR RUGRATS',
      slug: 'acting-for-rugrats4',
      description:
        'This fast- paced, high energy class will introduce and explore the fundamental principles of Improvisation through simple short form games and exercises.  This class will help students strengthen their mental agility, creativity, ensemble work and patience in a fun and entertaining environment. If your child is interested in pursuing camera and film work in South Florida or beyond, this class is highly encouraged. ',
      age: '4-5-6',
      image: '/img/kids6.jpg',
      teacher: 'Elena Maria Garcia',
      shedule: 'Saturday mornings 9:00 - 9:45 am',
      days: '1/15, 1/22, 1/29, 2/5, 2/1, 2/19',
      duration: '6 weeks',
      price: 100,
      subtitle: 'Acting Classes for Kids & Adults that deliver results!',
      direccion: ['99 SW 14th Street', 33315],
      countInStock: 5,
    },
  ],
};

export default data;
